name = "RankingDifferences"
uuid = "1798185d-28e1-492f-bad0-0ffd3086b9ac"
authors = ["Lars Schütz"]
version = "0.1.0"

[deps]
DifferencesBase = "f7c07657-0d0a-4d46-b086-01df223a7b4f"

[compat]
DifferencesBase = "0.3.0, 0.5"
julia = "1.3"
